export const HACKATHON = {
  title: "2026 skysh",
  subtitle: "서울대 × 고려대 × 연세대 × 성균관대 × 한양대 연합 개발 대회",
  tagline:
    "아이디어 검증부터 MVP 개발, 현업 멘토링, 최종 발표까지 이어지는 5개 대학 연합 실전형 해커톤입니다.",
  registrationUrl: "https://forms.gle/2a6LBfbEY715mCPw7",
  instagramUrl: "https://www.instagram.com/skysh_official",
  instagramHandle: "@skysh_official",
  dates: "6.22, 6.28, 7.12",
  phase1Place: "올댓마인드 문래점",
  finalPlace: "AWS Korea 강남 사옥",
  confirmationDate: "6.22(월)",
  sponsors: [
    {
      name: "AWS",
      accent: "#ff9900",
      logo: "sponsors/aws.svg",
    },
    {
      name: "Upbit",
      accent: "#0062df",
      logo: "sponsors/upbit.svg",
    },
    {
      name: "Hyundai Mobis",
      accent: "#00aad2",
      logo: "sponsors/hyundai-mobis.svg",
    },
    {
      name: "Jane Street",
      accent: "#1f63ff",
      logo: "sponsors/jane-street.svg",
    },
  ],
  schedule: [
    {
      date: "6.22",
      day: "월",
      title: "참가자 확정 및 안내",
      sub: "선발 결과와 행사 세부 안내",
      phase: "notice" as const,
      major: false,
      range: false,
    },
    {
      date: "6.28",
      day: "일",
      title: "1차 개발 밋업",
      sub: "아이디어 및 프로토타입 심사",
      phase: "phase1" as const,
      major: true,
      range: false,
    },
    {
      date: "7.12",
      day: "일",
      title: "2차 최종 발표",
      sub: "프로덕트 및 BM 심사",
      phase: "phase2" as const,
      major: true,
      range: false,
    },
  ],
  posterNotes: {
    phase1Summary: "1차 개발 밋업: 아이디어 및 프로토타입 심사",
    phase1Details: [
      "당일 진행되는 MVP 방식의 개발 밋업입니다",
      "150명, 약 40팀 중 12팀을 선발합니다",
      "개발 환경, 식사와 간식 제공",
    ],
    mentoring: "2차 최종 발표 전 AWS 측 멘토링이 있을 예정입니다",
    finalSummary: "2차 최종 발표: 프로덕트 및 BM 심사",
    finalDetails: [
      "실제 사용자 지표와 비즈니스 모델 타당성을 중심으로 심사합니다",
      "심사 후 최종 순위를 확정하고 시상을 진행합니다",
    ],
  },
  benefits: [
    "150명, 약 40팀 중 12팀 선발",
    "2차 최종 발표 전 AWS 멘토링",
    "개발 환경, 식사와 간식 제공",
    "프로덕트 및 BM 구체화",
  ],
  awardNote: "상금은 추후 변동될 수 있습니다.",
  awards: [
    { rank: "대상", prize: "150만원" },
    { rank: "금상", prize: "70만원" },
    { rank: "은상", prize: "50만원" },
    { rank: "동상", prize: "40만원" },
    { rank: "특별상", prize: "10만원" },
  ],
  application: {
    period: "접수 마감 6/20(토)",
    target: "서울대·고려대·연세대·성균관대·한양대 재학생·휴학생·대학원생",
    teamRule: "개인 또는 2-4명 팀으로 신청할 수 있습니다",
    personalRule:
      "개인 참가자는 신청서의 희망 개발 분야와 경험을 바탕으로 운영진이 팀을 배정합니다",
    teamRuleDetail: "팀 참가자는 2-4명으로 팀을 구성해 신청합니다",
    mixedTeamRule: "타교 학생과 구성한 연합팀도 참가할 수 있습니다",
    clubRule: "각 학교 소속 학생이면 동아리 소속이 아니어도 참가할 수 있습니다",
  },
  clubContacts: [
    {
      school: "서울대학교",
      club: "SCSC",
      contact: "scsc.snu@gmail.com",
      color: "var(--snu-ui)",
    },
    {
      school: "고려대학교",
      club: "KUCC",
      contact: "anamkucc314@gmail.com",
      color: "var(--korea-ui)",
    },
    {
      school: "연세대학교",
      club: "YCC",
      contact: "ycc@ycc.club",
      color: "var(--yonsei-ui)",
    },
    {
      school: "성균관대학교",
      club: "Comit",
      contact: "comit.skku@gmail.com",
      color: "var(--skku-ui)",
    },
    {
      school: "한양대학교",
      club: "Forif",
      contact: "https://forif.org",
      color: "var(--hanyang-ui)",
    },
  ],
} as const;
